# Generated by Django 3.0.8 on 2020-08-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Customer code')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Common nickname')),
                ('customer_full_name', models.CharField(max_length=100, verbose_name='Full name')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Phone number')),
                ('location', models.TextField(verbose_name='Customer address')),
                ('opening_balance', models.FloatField(blank=True, null=True, verbose_name='Opening balance')),
                ('balance', models.FloatField(verbose_name='Balance')),
            ],
        ),
    ]
