# Generated by Django 3.1 on 2020-09-21 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=20, verbose_name='Receipt number')),
                ('payer', models.CharField(blank=True, max_length=50, null=True, verbose_name='Payer')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Customer')),
            ],
        ),
    ]
