# Generated by Django 3.0.8 on 2020-11-06 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20201011_1719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashReceipt',
        ),
    ]
