# Generated by Django 3.0.8 on 2020-08-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_code', models.CharField(max_length=1, unique=True, verbose_name='VAT code')),
                ('code_name', models.CharField(max_length=10, verbose_name='VAT code name')),
                ('code_percentage', models.IntegerField(verbose_name='VAT percentage')),
            ],
        ),
    ]
