# Generated by Django 3.0.8 on 2020-11-06 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_delete_cashreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0012_auto_20201106_1513'),
        ('accounts', '0003_delete_cashaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CashReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(verbose_name='Date')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Receipt Number')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('slug', models.SlugField(default='')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.SalesInvoice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
