# Generated by Django 3.1.2 on 2020-11-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201109_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashreceiptitems',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
