# Generated by Django 3.0.8 on 2020-08-13 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50, verbose_name='Unit name')),
                ('unit_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('base_quantity', models.IntegerField(verbose_name='Minimum quantity')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=20, unique=True, verbose_name='Stock code')),
                ('stock_name', models.CharField(max_length=100, verbose_name='Name')),
                ('unit_name', models.CharField(default='unit', max_length=10, verbose_name='Unit name')),
                ('purchase_price', models.FloatField(verbose_name='Purchase price')),
                ('selling_price_1', models.FloatField(verbose_name='Selling price 1')),
                ('selling_price_2', models.FloatField(verbose_name='Selling price 2')),
                ('quantity_in', models.PositiveIntegerField(verbose_name='Quantity in')),
                ('quantity_out', models.PositiveIntegerField(verbose_name='Quantity out')),
                ('sales_discount', models.IntegerField(blank=True, null=True)),
                ('is_promotional', models.BooleanField(default=False)),
                ('stock_supplier', models.ManyToManyField(to='supplier.Supplier')),
                ('stock_vat_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.vat')),
                ('unit_of_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.UnitOfMeasurement')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='GoodsReturned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('return_number', models.CharField(max_length=50, verbose_name='Reference')),
                ('quantity_returned', models.IntegerField(verbose_name='Quantity')),
                ('goods_price', models.FloatField(verbose_name='Amount')),
                ('stock_code', models.ManyToManyField(to='inventory.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('receipt_number', models.CharField(max_length=50, verbose_name='Reference')),
                ('quantity_received', models.IntegerField(verbose_name='Quantity')),
                ('goods_price', models.FloatField(verbose_name='Buying price')),
                ('input_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Input by: ')),
                ('stock_code', models.ManyToManyField(to='inventory.Stock')),
            ],
        ),
    ]
