# Generated by Django 3.0.8 on 2020-08-13 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='quantity_in',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantity_out',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='unit_of_measurement',
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Base quantity'),
        ),
        migrations.AddField(
            model_name='unitofmeasurement',
            name='stock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='inventory.Stock'),
        ),
    ]
