# Generated by Django 3.0.8 on 2020-08-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stock_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='unit_quantity',
            field=models.IntegerField(default=1, help_text='Minimum amount of quantity in an item', verbose_name='Base unit quantity'),
        ),
    ]
