# Generated by Django 3.1 on 2020-08-25 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_stock_unit_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='goods_price',
        ),
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='quantity_received',
        ),
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='stock_code',
        ),
        migrations.CreateModel(
            name='ReturnedGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.FloatField(verbose_name='Buying price')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('document_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.goodsreceipt')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stock')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.FloatField(verbose_name='Buying price')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('document_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.goodsreceipt')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stock')),
            ],
        ),
    ]
