# Generated by Django 3.1 on 2020-08-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20200825_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
