# Generated by Django 3.1 on 2020-09-02 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_goodsreceipt_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedgoods',
            name='document_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_note', to='inventory.goodsreceipt'),
        ),
    ]
