# Generated by Django 3.1 on 2020-09-03 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20200902_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedgoods',
            name='unit_of_measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.unitofmeasurement'),
        ),
    ]
