# Generated by Django 3.1 on 2020-09-04 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0013_receivedgoods_unit_of_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreturned',
            name='goods_price',
        ),
        migrations.RemoveField(
            model_name='goodsreturned',
            name='quantity_returned',
        ),
        migrations.RemoveField(
            model_name='goodsreturned',
            name='stock_code',
        ),
        migrations.AddField(
            model_name='goodsreturned',
            name='input_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Input by: '),
        ),
        migrations.AddField(
            model_name='goodsreturned',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='returnedgoods',
            name='unit_of_measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.unitofmeasurement'),
        ),
    ]
