# Generated by Django 3.1 on 2020-09-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20200904_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofmeasurement',
            name='purchase_price',
            field=models.FloatField(default=0, verbose_name='Buying price'),
        ),
        migrations.AddField(
            model_name='unitofmeasurement',
            name='selling_price',
            field=models.FloatField(default=0, verbose_name='Selling price'),
        ),
    ]
