# Generated by Django 3.1 on 2020-09-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_unitofmeasurement_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasurement',
            name='base_quantity',
            field=models.FloatField(verbose_name='Minimum quantity'),
        ),
    ]
