# Generated by Django 3.1 on 2020-09-21 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_supplierpayment'),
        ('inventory', '0019_auto_20200915_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='goodsreturned',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
    ]
