# Generated by Django 3.0.8 on 2020-10-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_supplier_slug'),
        ('inventory', '0020_auto_20200921_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_supplier',
            field=models.ManyToManyField(blank=True, null=True, to='supplier.Supplier'),
        ),
    ]
