# Generated by Django 3.0.8 on 2020-10-14 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0022_remove_stock_selling_price_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockWriteOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_on_date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('write_on_number', models.CharField(max_length=50, verbose_name='Number')),
                ('input_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Input by')),
            ],
        ),
        migrations.CreateModel(
            name='StockWriteOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_on_date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('write_off_number', models.CharField(max_length=50, verbose_name='Number')),
                ('input_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Input by')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsWrittenOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('document_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_on_note', to='inventory.StockWriteOn')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Stock')),
                ('unit_of_measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.UnitOfMeasurement')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsWrittenOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('document_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_off_note', to='inventory.StockWriteOff')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Stock')),
                ('unit_of_measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.UnitOfMeasurement')),
            ],
        ),
    ]
