# Generated by Django 3.0.8 on 2020-10-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_supplier_slug'),
        ('inventory', '0023_goodswrittenoff_goodswrittenon_stockwriteoff_stockwriteon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_supplier',
            field=models.ManyToManyField(blank=True, to='supplier.Supplier'),
        ),
    ]
