# Generated by Django 3.0.8 on 2020-10-28 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_auto_20201023_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnedgoods',
            name='document_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.GoodsReturned'),
        ),
    ]
