# Generated by Django 3.0.8 on 2020-10-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_auto_20201028_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockwriteon',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
