# Generated by Django 3.0.8 on 2020-11-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_stockwriteon_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockwriteoff',
            old_name='write_on_date',
            new_name='write_off_date',
        ),
    ]
