# Generated by Django 3.1.2 on 2020-11-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_auto_20201102_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodswrittenoff',
            name='quantity',
            field=models.FloatField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='goodswrittenon',
            name='quantity',
            field=models.FloatField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='receivedgoods',
            name='quantity',
            field=models.FloatField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='returnedgoods',
            name='quantity',
            field=models.FloatField(verbose_name='Quantity'),
        ),
    ]
