# Generated by Django 3.1.2 on 2020-11-03 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_supplier_slug'),
        ('inventory', '0029_auto_20201103_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceipt',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
        migrations.AlterField(
            model_name='goodsreturned',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
    ]
