# Generated by Django 3.1.2 on 2020-11-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_auto_20201103_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='supplier_ref',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Supplier's ref"),
        ),
        migrations.AddField(
            model_name='goodsreturned',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='stockwriteoff',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='stockwriteon',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
    ]
