# Generated by Django 3.1.2 on 2020-12-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_auto_20201130_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCardEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=250)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stock')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.unitofmeasurement')),
            ],
        ),
    ]
