# Generated by Django 3.0.8 on 2020-12-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_stockcardentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodswrittenoff',
            name='log_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='goodswrittenon',
            name='log_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='receivedgoods',
            name='log_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='returnedgoods',
            name='log_number',
            field=models.IntegerField(null=True),
        ),
    ]
