# Generated by Django 3.0.8 on 2020-12-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_auto_20201208_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='cost_price',
            field=models.FloatField(default=0, verbose_name='Cost price per unit'),
        ),
        migrations.AddField(
            model_name='stock',
            name='selling_price',
            field=models.FloatField(default=0, verbose_name='Selling price per unit'),
        ),
    ]
