# Generated by Django 3.0.8 on 2020-08-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30, verbose_name='Name')),
                ('postal_address', models.TextField(verbose_name='Postal Address')),
                ('telephone_1', models.CharField(max_length=14, verbose_name='Telephone 1')),
                ('telephone_2', models.CharField(blank=True, max_length=14, null=True, verbose_name='Telephone 2')),
                ('kra_pin', models.CharField(max_length=11, verbose_name='Company PIN number')),
                ('kra_vat', models.CharField(max_length=10, verbose_name='Company VAT number')),
            ],
        ),
    ]
