# Generated by Django 3.1 on 2020-09-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('sales', 'Sales'), ('accounts', 'Accounts')], default='Sales', max_length=50),
        ),
    ]
