# Generated by Django 3.0.8 on 2020-08-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Supplier code')),
                ('supplier_name', models.CharField(max_length=500, verbose_name='Name')),
                ('contacts', models.TextField(verbose_name='Contacts')),
                ('pin', models.CharField(max_length=11, unique=True, verbose_name='KRA PIN Number')),
                ('vat_number', models.CharField(max_length=10, verbose_name='VAT Number')),
            ],
        ),
    ]
