# Generated by Django 3.0.8 on 2020-08-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='vat_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='VAT Number'),
        ),
    ]
