# Generated by Django 3.1 on 2020-09-21 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20200814_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=50, verbose_name='Reference')),
                ('payer', models.CharField(blank=True, max_length=50, null=True, verbose_name='Payee')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier', verbose_name='Supplier')),
            ],
        ),
    ]
