# Generated by Django 3.0.8 on 2020-08-13 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(verbose_name='Date')),
                ('receipt_number', models.CharField(max_length=20, unique=True, verbose_name='Receipt number')),
                ('is_credit', models.BooleanField(default=False, verbose_name='To pay')),
                ('credit_account', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Temporary credit account')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='Total')),
                ('slug', models.SlugField(default='')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userprofile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReceiptVoid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SoldGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.FloatField(verbose_name='Selling price')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_item', to='inventory.Stock')),
                ('receipt_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_set', to='sales.SalesReceipt')),
            ],
        ),
    ]
