# Generated by Django 3.1 on 2020-09-06 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreceipt',
            name='credit_account',
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='debtors_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Credit customer'),
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='walkin_customer',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Walk in Customer'),
        ),
        migrations.AlterField(
            model_name='salesreceipt',
            name='salesman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
