# Generated by Django 3.1 on 2020-09-06 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20200904_2148'),
        ('sales', '0002_auto_20200906_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldgoods',
            name='unit_of_measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.unitofmeasurement'),
        ),
    ]
