# Generated by Django 3.1 on 2020-09-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_soldgoods_unit_of_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldgoods',
            name='void_sale',
            field=models.BooleanField(blank=True, null=True, verbose_name='Void item sale'),
        ),
    ]
