# Generated by Django 3.1 on 2020-09-09 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20200904_2148'),
        ('sales', '0004_soldgoods_void_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreceiptvoid',
            name='amount',
            field=models.FloatField(null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='salesreceiptvoid',
            name='price',
            field=models.FloatField(null=True, verbose_name='Selling price'),
        ),
        migrations.AddField(
            model_name='salesreceiptvoid',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_stock', to='inventory.stock'),
        ),
        migrations.AddField(
            model_name='salesreceiptvoid',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='salesreceiptvoid',
            name='receipt_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_items_set', to='sales.salesreceipt'),
        ),
        migrations.AddField(
            model_name='salesreceiptvoid',
            name='sale_item_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_items', to='sales.soldgoods'),
        ),
        migrations.AddField(
            model_name='salesreceiptvoid',
            name='unit_of_measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.unitofmeasurement'),
        ),
    ]
