# Generated by Django 3.1 on 2020-09-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20200915_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreceiptvoid',
            name='quantity',
            field=models.FloatField(null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='soldgoods',
            name='quantity',
            field=models.FloatField(verbose_name='Quantity'),
        ),
    ]
