# Generated by Django 3.1 on 2020-09-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20200915_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreceiptvoid',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='soldgoods',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Amount'),
        ),
    ]
