# Generated by Django 3.1.2 on 2020-10-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20200920_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreceipt',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Total'),
        ),
    ]
