# Generated by Django 3.1.2 on 2020-11-06 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_auto_20201103_1641'),
        ('sales', '0011_invoicegoodsreturns_salesinvoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesinvoice',
            old_name='sale_date',
            new_name='invoice_date',
        ),
        migrations.CreateModel(
            name='InvoiceGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('price', models.FloatField(verbose_name='Selling price')),
                ('vat', models.FloatField(default=0, verbose_name='VAT')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('credit_note', models.BooleanField(blank=True, null=True, verbose_name='Void item sale')),
                ('invoice_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items_set', to='sales.salesinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_stock_item', to='inventory.stock')),
                ('unit_of_measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.unitofmeasurement')),
            ],
        ),
    ]
