# Generated by Django 3.1.2 on 2020-11-20 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_auto_20201116_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicegoods',
            name='credit_note',
            field=models.BooleanField(blank=True, null=True, verbose_name='Credit sale'),
        ),
        migrations.AlterField(
            model_name='invoicegoodsreturns',
            name='sale_item_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='sales.invoicegoods'),
        ),
    ]
