# Generated by Django 3.0.8 on 2020-12-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_auto_20201120_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicegoods',
            name='log_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='invoicegoodsreturns',
            name='log_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='salesreceiptvoid',
            name='log_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='soldgoods',
            name='log_number',
            field=models.IntegerField(null=True),
        ),
    ]
