# Generated by Django 3.0.8 on 2020-12-27 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0005_delete_cashreceipt'),
        ('inventory', '0035_auto_20201220_1514'),
        ('sales', '0015_auto_20201220_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn_date', models.DateTimeField(verbose_name='Date')),
                ('cn_number', models.CharField(max_length=20, unique=True, verbose_name='Credit note number')),
                ('total', models.FloatField(blank=True, default=0, null=True, verbose_name='Total')),
                ('slug', models.SlugField(default='')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='Credit customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.SalesInvoice')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ValueCreditItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Describe reason for value', max_length=500)),
                ('amount', models.FloatField()),
                ('cn_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.CreditNote')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnsCreditItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(null=True, verbose_name='Quantity')),
                ('price', models.FloatField(null=True, verbose_name='Selling price')),
                ('vat', models.FloatField(default=0, verbose_name='VAT')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('log_number', models.IntegerField(null=True)),
                ('cn_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.CreditNote')),
                ('invoice_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returns_items_set', to='sales.SalesInvoice')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returns_stock', to='inventory.Stock')),
                ('sale_item_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returns_items', to='sales.InvoiceGoods')),
                ('unit_of_measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.UnitOfMeasurement')),
            ],
        ),
    ]
