# Generated by Django 3.1.2 on 2021-01-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_creditnote_returnscredititems_valuecredititems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicegoods',
            name='credit_note',
            field=models.BooleanField(blank=True, null=True, verbose_name='Credited sale'),
        ),
    ]
